### ISSUE TITLE
No API key on built jar version

### ISSUE THREAD

**Issue by PhieF** [ialejandro/filebot-compiler#2]
Hi,

grabbing info from TVDB on TMDB is impossible with your final jar built since I guess you didn't pu api keys in 
filebot/source/net/filebot/Settings.properties

Thanks for your work !

**Comment by ialejandro** [comment]
I know. I think the original author remove his apikey, because he published the app in Windows Store (20$, I think) and tries you buy app (it's normal because spend his time programming hahaha). 

If you need use the program, you can use the latest version which works: https://filebot.ialejandro.rocks/Filebot_4.7.19_(d3c7028).jar

Sorry, I'll try to resolve as soon as possible :)

**Comment by PhieF** [comment]
Well it doesn't seem to work because of that (tried yesterday ! :) )

I would have liked to buy his app but can't find last version for linux even by buying it

**Comment by ialejandro** [comment]
He only support MacOS and Windows, look the propierties (https://github.com/filebot/filebot/blob/master/app.properties):
```
# Store
link.mas: macappstore://itunes.apple.com/app/id905384638
link.mws: ms-windows-store://review/?ProductId=9NBLGGH52T9X
```

I will search how to insert new API keys in the source code.

**Comment by PhieF** [comment]
So, I've filled the keys on my side directly in the jar (couldn't build, dependency issue even with ivy cache) and I've also had to fill net/filebot/media/ReleaseInfo.properties with urls provided on original jar (index of tvdb and tmdb)

**Comment by ialejandro** [comment]
If you want a stable version, check this repo: https://github.com/Phoenix09/filebot/releases. I need a lot of time to improve my code...
